print('                                                  Abril 4 2023📆  ')
print('                                                                   ')
print(' Carta para yo del futuro 📧📬                                    ')
print('                                                                   ')
print('Ahora estoy aprendiendo mucho sobre programacion, estoy adquiriendo ')
print('valioso conocimiento en diferentes lenguajes de programacion como  ')
print('lo es java, python, c++, javaScript. Como la programacion tiene    ')
print('muchas ramas, espero que mi yo del futuro encuentre lo que le gusta')
print('y que sobretodo sea un apasionado por lo que haga.                 ')
print('                                                                   ')
print('                                          🔷 De: Santiago Duran    ')
print('                                          🔶 Para: Mi yo del futuro')